### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [sergeyshestak/messenger#1]
Looks good in general, but need to add a few fixes:
  1. ![image](https://user-images.githubusercontent.com/5592397/88582617-aeb43800-d057-11ea-92a9-57253fc5b330.png)

  2. Also please add a few types of messages: link share, quoted text, video, audio

**Comment by sergeyshestak** [comment]
done

**Comment by IlyaMokin** [comment]
Looks fine, thanks, I am closing the review.
We will be checking your JS tasks soon
